---
 - hosts: node1
   become: True
   gather_facts: False
   tasks:
        - name: Installing httpd service
          yum:
             name: httpd
             state: present

        - name: Starting and enabling service      
          service:
             name: httpd
             state: started
             enabled: yes

 - hosts: node2
   become: True
   gather_facts: False
   tasks:
        - name: Installing mariadb service
          yum:
             name: 
                  - mariadb-server
                  - mariadb-common
             state: present

        - name: starting and enabling mariadb service
          service:
               name: mariadb
               state: started
               enabled: yes

...

